### ISSUE TITLE
Semantic meta improvements

### ISSUE THREAD

**Issue by romanowski** [romanowski/contextbuddy#6]
- [] Reuse loaded documents instead of loading them again and again
- [] Release scala meta with changes and try to get them open-sourced (or use metacp)
- [] New data kinds
